using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using Heroes5MapAPI.MapscriptGen.Scripting;

namespace Heroes5MapAPI.MapscriptGen
{
    public class MapscriptLUAWriter
    {
        private string _rootDirectory;

        public MapscriptLUAWriter(string rootDirectory)
        {
            this._rootDirectory = rootDirectory;
        }

        public FileInfo CreateMapscriptLUAFile()
        {
            string mapScriptLUAPath = (Path.Combine(this._rootDirectory, "mapscript.lua"));
            string scriptHeader = "-- mapscript.lua, generated by HOMMV Map Enhancer";
            using (StreamWriter writer = new StreamWriter(mapScriptLUAPath,true))
            {
                writer.WriteLine(scriptHeader);
            }

            FileInfo mapScriptLUAFile = new FileInfo(mapScriptLUAPath);
            return mapScriptLUAFile;
        }

        public void WriteScript()
        {
            Script script = new Script(Path.Combine(this._rootDirectory, "map.xdb"));
            script.GenerateScript();

            using (StreamWriter writer = new StreamWriter(Path.Combine(this._rootDirectory, "mapscript.lua"),true, Encoding.ASCII))
            {
                writer.Write(script.ToString());
            }
        }
    }
}
